[package]
name = "work-manager"
version = "0.1.2"
edition = "2024"
authors = ["Luuk Goossen"]
description = "A library for managing asynchronous work tasks."
license = "MIT"
repository = "https://github.com/luukgoossen/work-manager"
homepage = "https://github.com/luukgoossen/work-manager"
readme = "README.md"
keywords = ["workmanager", "work", "manager", "tokio", "async"]
categories = ["asynchronous", "concurrency"]
exclude = [".github/*"]

[dependencies]
tokio = { version = "1.48.0", features = [
	"rt",
	"rt-multi-thread",
	"time",
	"macros",
] }

[dev-dependencies]
tokio = { version = "1.48.0", features = [
	"rt",
	"rt-multi-thread",
	"time",
	"macros",
	"sync",
] }
